# Site
repository: cportet/cportet.github.io
favicon: images/favicon.ico

# Personal info
name: Cyril Portet
title: Project Manager
email: cyril@portet.org
#website: www.portet.org

darkmode: true

# Social links
skype_id: cyril-portet
#twitter_username: cportet
#github_username:  cportet
# dribbble_username: jekyll
#facebook_username: cyril.portet
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: cportet
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Additionnal icon links
additional_links:

 - title: Home
   icon: fas fa-home
   samesite: true
   url: https://www.portet.org
   
 - title: LinkedIn
   icon: fab fa-linkedin-in
   url: https://linkedin.portet.org

 - title: Mon CV au Format PDF
   icon: far fa-file-pdf
   url: https://cv.portet.org


# Additionnal icon links
additional_links_simple:

 - title: Twitter
   icon: fab fa-twitter
   url: https://twitter.portet.org

 - title: Facebook
   icon: fab fa-facebook
   url: https://facebook.portet.org

 - title: Instagram
   icon: fab fa-instagram
   url: https://instagram.portet.org

 - title: Mon CV en ligne
   icon: far fa-address-card
   samesite: true
   url: https://www.portet.org/resume

# About Section
about_title: A propos
about_profile_image: images/profile.jpg
#about_profile_image_simple: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **Important** : Je ne suis pas en recherche de nouvelles opportunités professionnelles actuellement.
  
  &nbsp;
  
  Bonjour,

  Je dispose de plus de 20 ans d'expérience dans le développement infomatique, la gestion de projet et le management d'équipe (ou d'environnement) IT.
  
  Aussi bien à l'aise en environnement Agile que sur des approches Waterfall, j'associe mon expertise technique acquise en tant que développeur, particulièrement
  en environnement Microsoft (.NET) avec mes capacités relationnelles et de gestion de projet avec comme double objectif, la satisfaction utilisateur et la qualité logicielle.

  Mon expertise se porte particulièrement sur la gestion de projet **Agile** (**Scrum**) et le **Management**.

  Techniquement, je suis très à l'aise avec le Web et particulièrement avec **.NET**.

  Je suis de nationalité Française, originaire de Picardie (Oise).
  
  J'ai vécu ou travaillé en Picardie, Ile de France et Belgique et je suis désormais installé en région lyonnaise ou je travaille chez un éditeur logiciel.

  &nbsp;
  
  Pour en savoir plus sur mon parcours professionnel, vous pouvez télécharger mon <a href="https://cv.portet.org" target="_blank">CV au format PDF</a> ou consulter mon [profil LinkedIn](https://linkedin.portet.org).
# Projects Section
projects_title: Compétences

# Experience Section
experience_title: Dernières expériences

# Education Section
education_title: Cursus

# More Section
more_title: En savoir plus sur moi
more_content: | # this will include new lines to allow paragraphs
  Dans le cadre de mon activité au sein de la DG Trésor, j'ai été habilité **CD** (Confidentiel Défense) en 2014.

  Je dispose du Permis de conduire (France) et d'un véhicule personnel.

  En sus de mes intérêts dans le développement informatique, l'agilité et la gestion de projets, mes autres intérêts portent sur :
   - Mes 3 enfants et les activités en leur compagnie
   - Les jeux vidéos
   - La politique et l'économie
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock"
 ]
