# Site
repository: cportet/cportet.github.io
favicon: images/favicon.ico

# Personal info
name: Cyril Portet
title: Chef de projet / Manager
email: cyril@portet.org
#website: www.portet.org

darkmode: true

# Social links
#twitter_username: cportet
#github_username:  cportet
# dribbble_username: jekyll
#facebook_username: cyril.portet
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: cportet
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Additionnal icon links
additional_links:

 - title: Mon CV
   icon: fa-readme
   url: https://www.portet.org/cv

# About Section
about_title: Welcome
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 
  Bienvenue.

# Projects Section
#projects_title: Compétences

# Experience Section
#experience_title: Dernières expériences

# Education Section
#education_title: Cursus

# More Section
#more_title: En savoir plus sur moi
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock"
 ]