# Site
repository: cportet/cportet.github.io
favicon: images/favicon.ico

# Personal info
name: Cyril Portet
title: Chef de projet / Manager
email: cyril@portet.org
#website: www.portet.org

darkmode: true

# Social links
twitter_username: cportet
#github_username:  cportet
# dribbble_username: jekyll
facebook_username: cyril.portet
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: cportet
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Additionnal icon links
additional_links:
 - title: Mon CV
   icon: fa-user-tag
   url: https://www.portet.org/ressources/CV-PORTET-CYRIL.pdf

# About Section
about_title: A mon sujet
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour,

  Je me présente : Cyril Portet - 40 ans ; plus de 20 ans d'expérience dans le développement infomatique et la gestion de projet.
  
  Aussi bien à l'aise en environnement Agile que sur des approches Waterfall, j'associe mon expertise technique acquise en tant que développeur, particulièrement
  en environnement Microsoft (.NET) avec mes capacités relationnelles et de gestion de projet avec comme double objectif, la satisfaction utilisateur et la qualité logicielle.

  Mon expertise se porte particulièrement sur la gestion de projet <mark>Agile</mark> et le <mark>Management</mark>.

  Techniquement, je suis très à l'aise avec le Web et particulièrement avec <mark>.NET</mark>.

  Je suis de nationalité Française, originaire de Picardie (Oise), j'ai vécu ou travaillé en Picardie, Ile de France et Belgique.
  
  Actuellement en Belgique, je travaille pour le compte de l'administration française.


  Pour en savoir plus sur moi, vous pouvez  consulter mon [profil LinkedIn](https://cv.portet.org) ou télécharger mon <a href="ressources/CV-PORTET-CYRIL.pdf" target="_blank">CV au format PDF</a>.

# Projects Section
projects_title: Compétences

# Experience Section
experience_title: Expérience

# Education Section
education_title: Formation

# More Section
more_title: En savoir plus sur moi
more_content: | # this will include new lines to allow paragraphs
  En sus de mes intérêts dans le développement informatique, l'agilité et la gestion de projets, mes autres intérêts portent sur :
   - Mes 3 enfants et les activités en leur compagnie (jeux de société, jeux vidéos)
   - Les jeux vidéos
   - La politique et l'économie
  
  Vous pouvez aussi me retrouver ailleurs sur Internet : 
    - [sur Twitter](https://twitter.portet.org)
    - [sur Facebook](https://facebook.portet.org)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "docs/"
 ]