//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomePage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyHomePage.AppRessources", typeof(AppRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compétences.
        /// </summary>
        public static string Competences_Competences_Title {
            get {
                return ResourceManager.GetString("Competences_Competences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaine.
        /// </summary>
        public static string Competences_Domaine_Title {
            get {
                return ResourceManager.GetString("Competences_Domaine_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger le CV (Format PDF).
        /// </summary>
        public static string File_FileKind_CV_DownloadTitle {
            get {
                return ResourceManager.GetString("File_FileKind_CV_DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum vitae de Cyril Portet.
        /// </summary>
        public static string File_FileKind_CV_SubTitle {
            get {
                return ResourceManager.GetString("File_FileKind_CV_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon CV.
        /// </summary>
        public static string File_FileKind_CV_Title {
            get {
                return ResourceManager.GetString("File_FileKind_CV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger mon CV.
        /// </summary>
        public static string HeaderMenu_CV_Title {
            get {
                return ResourceManager.GetString("HeaderMenu_CV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer ce site en tant qu&apos;application.
        /// </summary>
        public static string HeaderMenu_Install_Title {
            get {
                return ResourceManager.GetString("HeaderMenu_Install_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter mon profil LinkedIn.
        /// </summary>
        public static string HeaderMenu_LinkedIn_Title {
            get {
                return ResourceManager.GetString("HeaderMenu_LinkedIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la page précédente.
        /// </summary>
        public static string MainLayout_GoBack_Title {
            get {
                return ResourceManager.GetString("MainLayout_GoBack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème clair.
        /// </summary>
        public static string MainLayout_Theme_Clair {
            get {
                return ResourceManager.GetString("MainLayout_Theme_Clair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème sombre.
        /// </summary>
        public static string MainLayout_Theme_Sombre {
            get {
                return ResourceManager.GetString("MainLayout_Theme_Sombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu.
        /// </summary>
        public static string MainLayout_ToggleMenuTitle_Afficher {
            get {
                return ResourceManager.GetString("MainLayout_ToggleMenuTitle_Afficher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer le menu.
        /// </summary>
        public static string MainLayout_ToggleMenuTitle_Masquer {
            get {
                return ResourceManager.GetString("MainLayout_ToggleMenuTitle_Masquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MàJ.
        /// </summary>
        public static string MainLayout_Updater_Button {
            get {
                return ResourceManager.GetString("MainLayout_Updater_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle version disponible !.
        /// </summary>
        public static string MainLayout_Updater_Text {
            get {
                return ResourceManager.GetString("MainLayout_Updater_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier n&apos;a été fourni.
        /// </summary>
        public static string MyFullPageViewer_MissingFile {
            get {
                return ResourceManager.GetString("MyFullPageViewer_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger le fichier.
        /// </summary>
        public static string MyFullPageViewer_NotSupported_Download {
            get {
                return ResourceManager.GetString("MyFullPageViewer_NotSupported_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre navigateur ne peut pas afficher le fichier demandé..
        /// </summary>
        public static string MyFullPageViewer_NotSupported_Text {
            get {
                return ResourceManager.GetString("MyFullPageViewer_NotSupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une valeur....
        /// </summary>
        public static string MySelect_NullValue {
            get {
                return ResourceManager.GetString("MySelect_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer le menu.
        /// </summary>
        public static string NavMenu_CloseMenu_Title {
            get {
                return ResourceManager.GetString("NavMenu_CloseMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string NavMenu_Page_Applications {
            get {
                return ResourceManager.GetString("NavMenu_Page_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos.
        /// </summary>
        public static string NavMenu_Page_Apropos {
            get {
                return ResourceManager.GetString("NavMenu_Page_Apropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille.
        /// </summary>
        public static string NavMenu_Page_Famille {
            get {
                return ResourceManager.GetString("NavMenu_Page_Famille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string NavMenu_Page_Home {
            get {
                return ResourceManager.GetString("NavMenu_Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon CV.
        /// </summary>
        public static string NavMenu_Page_MonCV {
            get {
                return ResourceManager.GetString("NavMenu_Page_MonCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string NavMenu_Page_Options {
            get {
                return ResourceManager.GetString("NavMenu_Page_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string NavMenu_Page_Personnel {
            get {
                return ResourceManager.GetString("NavMenu_Page_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string NotFound_Home_Link {
            get {
                return ResourceManager.GetString("NotFound_Home_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La page n&apos;existe pas.
        /// </summary>
        public static string NotFound_PageSubTitle {
            get {
                return ResourceManager.GetString("NotFound_PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur 404.
        /// </summary>
        public static string NotFound_PageTitle {
            get {
                return ResourceManager.GetString("NotFound_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string NotFound_Retour_Link {
            get {
                return ResourceManager.GetString("NotFound_Retour_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, la page demandée n&apos;existe pas..
        /// </summary>
        public static string NotFound_Text {
            get {
                return ResourceManager.GetString("NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page non disponible.
        /// </summary>
        public static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos de cette application.
        /// </summary>
        public static string Page_About_SubTitle {
            get {
                return ResourceManager.GetString("Page_About_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos.
        /// </summary>
        public static string Page_About_Title {
            get {
                return ResourceManager.GetString("Page_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Page_Applications_Section_Contenu {
            get {
                return ResourceManager.GetString("Page_Applications_Section_Contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes applications et réalisations.
        /// </summary>
        public static string Page_Applications_SubTitle {
            get {
                return ResourceManager.GetString("Page_Applications_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Page_Applications_Title {
            get {
                return ResourceManager.GetString("Page_Applications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Page_Apps_Charte_Section_Sommaire {
            get {
                return ResourceManager.GetString("Page_Apps_Charte_Section_Sommaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charte.
        /// </summary>
        public static string Page_Apps_Charte_Title {
            get {
                return ResourceManager.GetString("Page_Apps_Charte_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé.
        /// </summary>
        public static string Page_Apps_MesApps_Section_Sommaire {
            get {
                return ResourceManager.GetString("Page_Apps_MesApps_Section_Sommaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Applications.
        /// </summary>
        public static string Page_Apps_MesApps_Title {
            get {
                return ResourceManager.GetString("Page_Apps_MesApps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le document demandé n&apos;existe pas.
        /// </summary>
        public static string Page_File_DocumentInconnu_SubTitle {
            get {
                return ResourceManager.GetString("Page_File_DocumentInconnu_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document inconnu.
        /// </summary>
        public static string Page_File_DocumentInconnu_Title {
            get {
                return ResourceManager.GetString("Page_File_DocumentInconnu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        public static string Page_Home_Section_Bienvenue {
            get {
                return ResourceManager.GetString("Page_Home_Section_Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon CV.
        /// </summary>
        public static string Page_Home_Section_CV {
            get {
                return ResourceManager.GetString("Page_Home_Section_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue chez moi.
        /// </summary>
        public static string Page_Home_SubTitle {
            get {
                return ResourceManager.GetString("Page_Home_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Page_Home_Title {
            get {
                return ResourceManager.GetString("Page_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer.
        /// </summary>
        public static string Page_Options_Button_Apply {
            get {
                return ResourceManager.GetString("Page_Options_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string Page_Options_Button_Reset {
            get {
                return ResourceManager.GetString("Page_Options_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Page_Options_Section_Options_Title {
            get {
                return ResourceManager.GetString("Page_Options_Section_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu de couleur :.
        /// </summary>
        public static string Page_Options_Select_ColorSet {
            get {
                return ResourceManager.GetString("Page_Options_Select_ColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue :.
        /// </summary>
        public static string Page_Options_Select_Language {
            get {
                return ResourceManager.GetString("Page_Options_Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème :.
        /// </summary>
        public static string Page_Options_Select_Theme {
            get {
                return ResourceManager.GetString("Page_Options_Select_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnalisation de l&apos;application.
        /// </summary>
        public static string Page_Options_SubTitle {
            get {
                return ResourceManager.GetString("Page_Options_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Page_Options_Title {
            get {
                return ResourceManager.GetString("Page_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me contacter.
        /// </summary>
        public static string Page_Perso_Section_MeContacter {
            get {
                return ResourceManager.GetString("Page_Perso_Section_MeContacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me retrouver.
        /// </summary>
        public static string Page_Perso_Section_MeRetrouver {
            get {
                return ResourceManager.GetString("Page_Perso_Section_MeRetrouver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui suis-je ?.
        /// </summary>
        public static string Page_Perso_Section_QuiSuisJe {
            get {
                return ResourceManager.GetString("Page_Perso_Section_QuiSuisJe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En savoir plus sur moi.
        /// </summary>
        public static string Page_Perso_SubTile {
            get {
                return ResourceManager.GetString("Page_Perso_SubTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string Page_Perso_Title {
            get {
                return ResourceManager.GetString("Page_Perso_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection.
        /// </summary>
        public static string Page_Redirection_Title {
            get {
                return ResourceManager.GetString("Page_Redirection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bref.
        /// </summary>
        public static string Page_Resume_EnBref_Title {
            get {
                return ResourceManager.GetString("Page_Resume_EnBref_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes compétences.
        /// </summary>
        public static string Page_Resume_MesCompetences_Title {
            get {
                return ResourceManager.GetString("Page_Resume_MesCompetences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil professionnel.
        /// </summary>
        public static string Page_Resume_MonProfil_Title {
            get {
                return ResourceManager.GetString("Page_Resume_MonProfil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui suis-je ?.
        /// </summary>
        public static string Page_Resume_QuiSuisJe_Title {
            get {
                return ResourceManager.GetString("Page_Resume_QuiSuisJe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter mon expérience détaillée et téléchargez mon CV.
        /// </summary>
        public static string Page_Resume_SubTitle {
            get {
                return ResourceManager.GetString("Page_Resume_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon CV.
        /// </summary>
        public static string Page_Resume_Title {
            get {
                return ResourceManager.GetString("Page_Resume_Title", resourceCulture);
            }
        }
    }
}
